language: java

jdk:
  - openjdk11

dist: xenial

sudo: required

addons:
  chrome: stable

before_cache:
  - rm -rf  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/
    - $HOME/.m2/

install: true

script:
  - ./gradlew test
