language: java

jdk:
  - openjdk11

dist: xenial

sudo: required

addons:
  chrome: stable

before_cache:
  - rm -rf  $HOME/.gradle/caches/

cache:
  directories:
    - $HOME/.gradle/

install: true

script:
  - ./gradlew clean test
